const bcrypt = require("bcryptjs");

const data = {
  users: [
    {
      name: "Super Admin",
      email: "0ikko@gmail.com",
      phone: "01901234567",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Admin",
      email: "admin@gmail.com",
      phone: "01901234568",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Roman",
      email: "user@gmail.com",
      phone: "01901234569",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],

  category: [
    {
      MainCategory: "Women's Plaza",
      Category: [
        {
          Saree: [
            "Cotton",
            "Silk",
            "Katan",
            "Muslin",
            "Jamdani",
            "Georgette",
            "Nakshi Kantha",
            "Linen",
            "Batik",
            "Khadi",
            "Tangail Taant",
            "Monipuri",
            "Chemical Free & Natural Dye",
            "Rajshahi Silk",
            "Dhakai Benaroshi",
          ],
          Salwar_Kameez: [
            "Cotton",
            "Silk",
            "Katan",
            "Muslin",
            "Jamdani",
            "Georgette",
            "Linen",
            "Batik",
            "Khadi",
            "Natural Dye",
          ],
          Shawl: ["Nakshi Kantha", "Silk", "Viscose", "Cotton"],

          Jewellery: [
            "Tip",
            "Toe Ring",
            "Hair Accessories",
            "Hijab Pins",
            "Saree Clips",
            "Tikli",
            "Waist Chain",
            "Armlet",
            "Brooches And Pins",
            "Rings",
            "Bracelets",
            "Bangles And Churies",
            "Lockets And Pendants",
            "Jewellery Boxes",
            "Earrings",
            "Necklaces",
            "Jewellery Set",
          ],
          Islamic_Fashion: [
            "Abaya",
            "Long Coat",
            "Cape/ Kaftan",
            "Hijab",
            "Niqab",
            "Burka",
          ],
          Shoes: [
            "Doctors Shoes",
            "Heels",
            "Nagras",
            "Sneakers",
            "Boots, Wellington Boots And Booties",
            "Ballet Flats",
            "Loafers And Moccasins",
            "Slippers And Flip Flops",
            "Sandals",
            "Pumps",
          ],
          Bags: [
            "Hand Bag",
            "Boston Bags",
            "Tote Bags",
            "Shoulder Bags",
            "Belt Bags",
            "Baguette Bags",
            "Backpacks",
            "Mini Bags",
            "Clutch Bags",
            "Batua Bags",
            "Wallets, File Cover & Small Accessories",
            "Purses",
            "Travel Bags ",
            "Laptop Bags ",
            "Messenger Bags  ",
            "Lunch Bags ",
            "Carry Bags ",
            "Duffel Bags",
            "Makeup Boxes/ Bags ",
            "Mobile Bag/ Cover  ",
            "College Bag ",
            "Peekaboo Bags  ",
          ],
          PantsAndShorts: [
            "Denim Jeans",
            "Leggings & Jeggings",
            "Trousers & Capris",
            "Palazzo Pants",
            "Baggy pants",
            "Bell Bottom Pants",
            "Jumpsuits",
            "Sweatpants",
          ],
          Others: [
            "Yokes",
            "Belts",
            "Watches & Covers",
            "Sunglasses & Cover",
            "Hats, Gloves, Socks & Tights",
            "Panjabi",
            "Kurtas",
            "Koti & Waistcoats",
            "Gown",
            "Scarves",
            "Tops, T-Shirts, Polo Shirts & Shirts",
            "Frocks, Skirts, Tunic & Shrug",
            "Sweatshirts",
            "Coats & Jackets",
            "Sweaters & Cardigans",
            "Motherhood Clothing/ Maternity Dress",
          ],
        },
      ],
    },

    {
      MainCategory: "Men's Plaza",
      Category: [
        {
          Panjabi: [
            "Cotton",
            "Endi cotton",
            "Khadi",
            "Linen",
            "Georgette",
            "Silk",
            "Endi Silk",
            "Katan",
            "Jamdani",
            "Muslin",
            "Nakshi Kantha",
            "Chemical Free & Natural Dye",
          ],
          Pajamas: [
            "Aligari",
            "Churidars",
            "Dhoti Salwar",
            "Patiala Salwar",
            "Harem Salwar",
            "Afghani Salwar",
            "Simple Salwar",
            "Straight Salwar",
          ],
          Shirts: [
            "Formal/ Official/ Executive",
            "Casual",
            "Party",
            "Denim Shirt",
            "Cotton",
            "Silk",
            "Katan",
            "Muslin",
            "Jamdani",
            "Georgette",
            "Nakshi Kantha",
            "Linen",
            "Batik",
            "Khadi",
            "Chemical Free & Natural Dye Shirts",
          ],
          PantsAndShorts: [
            "Official",
            "Khakis Pants",
            "Denim Jeans",
            "Joggers/ Trousers & Sweatpants",
            "Shorts",
          ],
          Shoes: [
            "Sandals",
            "Traditional Lace Shoes",
            "Canvas Shoes",
            "Flip Flops (dui fita)",
            "Convers",
            "Loafers",
            "Nagras",
            "|Sneakers",
          ],
          MensEssentialsAndAccessories: [
            "Wallets, Card Holders, File Folder & Small Accessories",
            "Bag",
            "Belts & Suspenders",
            "Sunglasses & Sunglass covers",
            "Caps, Hats & Gloves",
            "Ties",
            "Handkerchief/ Rumal & Pocket square",
            "Umbrella",
            "Watches, Cufflinks & Jewellery",
            "Scarves",
            "Socks",
            "Luggage & Travel Bags",
          ],
          Others: [
            "Coaty",
            "Fotua",
            "Shirts",
            "T-Shirts",
            "Kurta",
            "Coats",
            "Jackets",
            "Blazers, Suits & Waistcoats",
            "Hoodies & Sweatshirts",
            "Sweaters & Cardigans",
            "Shawl",
            "Lungi",
            "Gamcha",
          ],
        },
      ],
    },
    {
      MainCategory: "Kid's Plaza",
      Category: [
        {
          BoysClothing: [
            "Panjabi",
            "Pajamas",
            "Panjabi Pajama set",
            "Shirt",
            "Pant",
            "Shirt Pant set",
            "T-shirt",
            "Polo",
            "Fatua",
            "Nima",
          ],
          GirlsClothing: [
            "Frock",
            "Salwar Kameez",
            "Top",
            "Skirt top",
            "Pant top",
            "Nima",
            "Ghagra choli",
            "Saree",
          ],
          Others: [
            "Bags",
            "Baby Jewellery",
            "Baby Kantha",
            "Suits, Blazers, Waistcoats",
            "Sweaters, Cardigans",
            "Hoodies, Caps",
            "Accessories",
          ],
          Footwears: ["Sandals", "Shoes"],
          Toys: ["Soft", "Wooden", "Jute", "Plastic"],
          SchoolItems: ["Schoolbags", "School Dress", "Schoolbags"],
        },
      ],
    },
    {
      MainCategory: "Wedding Plaza",
      Category: [
        {
          other: ["Men", "Women", "Accessories"],
        },
      ],
    },
    {
      MainCategory: "Family Fashion Plaza",
    },
    {
      MainCategory: "Health Beauty & Personal Care Plaza",
      Category: [
        {
          BeautyAndCare: [
            "Hair care",
            "Skin Care",
            "Bath & Body",
            "Fragrance",
            "Healthcare",
            "Shave & Hair Removal",
            "Cleaners & Disinfectants",
          ],
        },
      ],
    },
    {
      MainCategory: "Home & Art of Living",
      Category: [
        {
          Living: [
            "Cushion Covers",
            "Pillow Covers",
            "Curtains",
            "Bed Sheets",
            "Rugs and Carpets",
            "Sofa Backs",
            "Nakshi Kantha",
            "Blanket",
          ],
          Dining: [
            "Cups, Mugs & Jugs",
            "Plates & Platters",
            "Bowls",
            "Trays",
            "Cutlery & Utensils",
            "Runners Set",
            "Placemat",
            "Napkins & Apron",
            "Tablecloths",
            "Napkin Holders",
            "Coasters",
            "Clay Crockery",
          ],
          Decor: [
            "Mirrors",
            "Wall/Door Hangings",
            "Photo Frames",
            "Boxes",
            "Candles",
            "Lanterns & Candle Stands",
            "Flower Vase",
            "Lamps & Shades",
            "Musical Instruments",
            "Decorative Items",
            "Brass Novelties",
            "Cast Iron Novelties",
            "Wooden Accents",
            "Bonsai",
            "Planters",
            "Religious Accessories",
            "Baskets",
          ],
          GiftsAndStationery: [
            "Gift Cards & Accessories",
            "Notebook",
            "Gift Box",
            "Wrapping Accessories",
            "Desk Accessories",
          ],
        },
      ],
    },
    {
      MainCategory: "Food Plaza",
      Category: [
        {
          Foods: [
            "Bread & Bakery",
            "Dairy Products",
            "Snacks",
            "Frozen Food",
            "Beverages",
            "Honey",
            "Food Ingredients",
            "Instant Food",
            "Grains, Beans and Nuts",
            "Cooking Essentials",
            "Ready Food/ Cooked Food",
            "Preserved Foods & Accessories",
            "Dry Food",
            "Dessert",
          ],
        },
      ],
    },
    {
      MainCategory: "Oikko Agro Plaza",
    },
    {
      MainCategory: "Machines & Machinery Plaza",
      Category: [
        {
          Others: [
            "Agricultural Machinery & Equipment",
            "Industrial Machinery & Equipment",
            "Automotive Parts",
          ],
        },
      ],
    },
  ],

  products: [
    {
      name: "Cotton Face Mask",
      mainCategory: "Womens's Plaza",
      category: "Cotton Silk Saree",
      subCategory: "Saree",
      DisplayImage:
        "https://dtt1c9id3txwq.cloudfront.net/assets/images/001/174/827/large/20-Cotton_Face_Mask.jpg?1618040405",
      productDetailsImgs: [
        "https://dtt1c9id3txwq.cloudfront.net/assets/images/001/174/827/large/20-Cotton_Face_Mask.jpg?1618040405",
        "https://dtt1c9id3txwq.cloudfront.net/assets/images/001/174/827/large/20-Cotton_Face_Mask.jpg?1618040405",
        "https://dtt1c9id3txwq.cloudfront.net/assets/images/001/174/827/large/20-Cotton_Face_Mask.jpg?1618040405",
      ],
      isTrading: true,
      sellPrice: 80.0,
      costPrice: 80.0,
      productTexPrice: 1.0,
      productCode: "RTP-104",
      productDisplay: true,
      countInStock: 10,
      color: ["White Maroon"],
      Material: ["Cotton"],
      Size: ["L-8.5", "W-5.2"],
      Feature: "Four Layer",
      Measurement: ["w-20", "h-36"],
      PlaceOfOrigin: "Bangladesh",
      brand: "Rifat Sultana",
      rating: 0,
      numReviews: 0,
      description:
        "typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      ShippingAndReturnPolicy:
        "Free delivery for more than 5000 BDT shopping, Delivery charge: Inside Dhaka City 40 BDT Outside Dhaka City 80 BDT, Delivery time: Inside Dhaka City- Within 48 hours; Outside Dhaka City- Within 72 hours, Payment method: Cash on Delivery (Only for Dhaka), Bkash, Rocket, MasterCard, Visa Card, American Express and all bank wire transfer supported by SSLCommerz, Return Policy: Call us or inbox us within 3 days of purchase, if the product has any defect or is not the same one you ordered. However, the product will not be taken back without the tags intact and without in their original packaging, in a washed and/or damaged condition.",
    },
  ],
};

module.exports = data;
